# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1

apiVersion: v1
kind: PersistentVolume
metadata:
  name: quarkus-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 50M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/h2"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quarkus-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
